SHOW DATABASES;
DROP DATABASE HIGHSCORES;
CREATE DATABASE IF NOT EXISTS HIGHSCORES;

USE HIGHSCORES;

SHOW TABLES;

CREATE TABLE IF NOT EXISTS HIGHSCORES (

    id INT AUTO_INCREMENT PRIMARY KEY,
    playername VARCHAR(255),
    score DECIMAL(7,2),
    playtime DATETIME DEFAULT CURRENT_TIMESTAMP
);


DESCRIBE HIGHSCORES;

INSERT INTO HIGHSCORES (playername, score) VALUES("olli k", "50");
INSERT INTO HIGHSCORES (playername, score) VALUES("alli k", "55");
INSERT INTO HIGHSCORES (playername, score) VALUES("kolli k", "58");
INSERT INTO HIGHSCORES (playername, score) VALUES("lolli k", "70");

SELECT * FROM HIGHSCORES ORDER BY score LIMIT 10;